'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Lock, Eye, EyeOff, Save, CheckCircle } from 'lucide-react';

export function AiSettings() {
    const [apiKey, setApiKey] = useState('');
    const [modelId, setModelId] = useState('google/gemini-3-flash-preview'); // User requested Gemini 3.0 Flash Preview
    const [useCloudSummaries, setUseCloudSummaries] = useState(false);
    const [showKey, setShowKey] = useState(false);
    const [saved, setSaved] = useState(false);

    useEffect(() => {
        const storedKey = localStorage.getItem('weekly_openrouter_key');
        const storedModel = localStorage.getItem('weekly_openrouter_model');
        const storedUseCloud = localStorage.getItem('weekly_use_cloud_for_summaries');

        if (storedKey) setApiKey(storedKey);
        if (storedModel) setModelId(storedModel);
        if (storedUseCloud) setUseCloudSummaries(storedUseCloud === 'true');
    }, []);

    const handleSave = () => {
        localStorage.setItem('weekly_openrouter_key', apiKey.trim());
        localStorage.setItem('weekly_openrouter_model', modelId.trim());
        localStorage.setItem('weekly_use_cloud_for_summaries', String(useCloudSummaries));
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
    };

    return (
        <Card className="border-indigo-100 dark:border-indigo-900">
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <Lock className="w-5 h-5 text-indigo-500" />
                    AI & Cloud Settings
                </CardTitle>
                <CardDescription>
                    Configure "Big Brain" mode using OpenRouter.
                </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="space-y-2">
                    <Label htmlFor="api-key">OpenRouter API Key</Label>
                    <div className="flex gap-2">
                        <div className="relative flex-1">
                            <Input
                                id="api-key"
                                type={showKey ? "text" : "password"}
                                value={apiKey}
                                onChange={(e) => setApiKey(e.target.value)}
                                placeholder="sk-or-..."
                                className="pr-10"
                            />
                            <button
                                type="button"
                                onClick={() => setShowKey(!showKey)}
                                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                            >
                                {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                            </button>
                        </div>
                    </div>
                </div>

                <div className="space-y-2">
                    <Label htmlFor="model-id">Cloud Model ID</Label>
                    <Input
                        id="model-id"
                        value={modelId}
                        onChange={(e) => setModelId(e.target.value)}
                        placeholder="google/gemini-2.0-flash-001"
                    />
                    <p className="text-[10px] text-muted-foreground">
                        Default: google/gemini-2.0-flash-001 (Gemini Flash).
                    </p>
                </div>

                <div className="flex items-center space-x-2 border p-3 rounded-md bg-indigo-50/50 dark:bg-indigo-900/20">
                    <input
                        type="checkbox"
                        id="use-cloud"
                        checked={useCloudSummaries}
                        onChange={(e) => setUseCloudSummaries(e.target.checked)}
                        className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600"
                    />
                    <div className="grid gap-1.5 leading-none">
                        <Label
                            htmlFor="use-cloud"
                            className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                        >
                            Use Cloud for Summaries
                        </Label>
                        <p className="text-[10px] text-muted-foreground">
                            If enabled, Daily/Weekly/Monthly summaries will be generated by the Cloud Model (Gemini) instead of Local Llama.
                        </p>
                    </div>
                </div>

                <Button onClick={handleSave} className="w-full" variant={saved ? "outline" : "default"}>
                    {saved ? (
                        <>
                            <CheckCircle className="w-4 h-4 mr-2 text-green-500" />
                            Saved
                        </>
                    ) : (
                        <>
                            <Save className="w-4 h-4 mr-2" />
                            Save Config
                        </>
                    )}
                </Button>

                <p className="text-xs text-muted-foreground pt-2 border-t">
                    Get a key at <a href="https://openrouter.ai/" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">openrouter.ai</a>.
                </p>
            </CardContent>
        </Card>
    );
}
